/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyReport {
  'msPrice' : number,
  'msTesting' : number,
  'msNozzles' : Array<Nozzle>,
  'hsdPrice' : number,
  'date' : string,
  'notes' : string,
  'deviceId' : string,
  'savedAt' : string,
  'hsdTesting' : number,
  'hsdNozzles' : Array<Nozzle>,
  'stationName' : string,
  'engineOilRows' : Array<EngineOilRow>,
  'deductionsTabs' : Array<DeductionsTab>,
}
export interface DeductionRow { 'expenseLabel' : string, 'amount' : number }
export interface DeductionsTab {
  'tabName' : string,
  'rows' : Array<DeductionRow>,
}
export interface EngineOilRow {
  'name' : string,
  'quantity' : number,
  'price' : number,
}
export interface Nozzle { 'closeReading' : number, 'openReading' : number }
export interface ReportEntry { 'id' : string, 'report' : DailyReport }
export interface _SERVICE {
  'deleteReport' : ActorMethod<[string], undefined>,
  'getReport' : ActorMethod<[string], [] | [DailyReport]>,
  'listReportDates' : ActorMethod<[], Array<string>>,
  'listReportsByDevice' : ActorMethod<[string], Array<ReportEntry>>,
  'saveReport' : ActorMethod<[string, DailyReport], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];