/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FuelData = IDL.Record({
  'pricePerLitre' : IDL.Float64,
  'closingReading' : IDL.Float64,
  'openingReading' : IDL.Float64,
});
export const Deduction = IDL.Record({
  'type' : IDL.Text,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const DailyReport = IDL.Record({
  'ms' : FuelData,
  'hsd' : FuelData,
  'deductions' : IDL.Vec(Deduction),
});

export const idlService = IDL.Service({
  'getReport' : IDL.Func([IDL.Text], [DailyReport], ['query']),
  'listReportDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'saveReport' : IDL.Func(
      [
        IDL.Text,
        FuelData,
        FuelData,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Float64)),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FuelData = IDL.Record({
    'pricePerLitre' : IDL.Float64,
    'closingReading' : IDL.Float64,
    'openingReading' : IDL.Float64,
  });
  const Deduction = IDL.Record({
    'type' : IDL.Text,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const DailyReport = IDL.Record({
    'ms' : FuelData,
    'hsd' : FuelData,
    'deductions' : IDL.Vec(Deduction),
  });
  
  return IDL.Service({
    'getReport' : IDL.Func([IDL.Text], [DailyReport], ['query']),
    'listReportDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'saveReport' : IDL.Func(
        [
          IDL.Text,
          FuelData,
          FuelData,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Float64)),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };