/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Nozzle = IDL.Record({
  'closeReading' : IDL.Float64,
  'openReading' : IDL.Float64,
});
export const EngineOilRow = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Float64,
  'price' : IDL.Float64,
});
export const DeductionRow = IDL.Record({
  'expenseLabel' : IDL.Text,
  'amount' : IDL.Float64,
});
export const DeductionsTab = IDL.Record({
  'tabName' : IDL.Text,
  'rows' : IDL.Vec(DeductionRow),
});
export const DailyReport = IDL.Record({
  'msPrice' : IDL.Float64,
  'msTesting' : IDL.Float64,
  'msNozzles' : IDL.Vec(Nozzle),
  'hsdPrice' : IDL.Float64,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'hsdTesting' : IDL.Float64,
  'hsdNozzles' : IDL.Vec(Nozzle),
  'engineOilRows' : IDL.Vec(EngineOilRow),
  'deductionsTabs' : IDL.Vec(DeductionsTab),
});

export const idlService = IDL.Service({
  'deleteReport' : IDL.Func([IDL.Text], [], []),
  'getReport' : IDL.Func([IDL.Text], [IDL.Opt(DailyReport)], ['query']),
  'listReportDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'saveReport' : IDL.Func([IDL.Text, DailyReport], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Nozzle = IDL.Record({
    'closeReading' : IDL.Float64,
    'openReading' : IDL.Float64,
  });
  const EngineOilRow = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const DeductionRow = IDL.Record({
    'expenseLabel' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const DeductionsTab = IDL.Record({
    'tabName' : IDL.Text,
    'rows' : IDL.Vec(DeductionRow),
  });
  const DailyReport = IDL.Record({
    'msPrice' : IDL.Float64,
    'msTesting' : IDL.Float64,
    'msNozzles' : IDL.Vec(Nozzle),
    'hsdPrice' : IDL.Float64,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'hsdTesting' : IDL.Float64,
    'hsdNozzles' : IDL.Vec(Nozzle),
    'engineOilRows' : IDL.Vec(EngineOilRow),
    'deductionsTabs' : IDL.Vec(DeductionsTab),
  });
  
  return IDL.Service({
    'deleteReport' : IDL.Func([IDL.Text], [], []),
    'getReport' : IDL.Func([IDL.Text], [IDL.Opt(DailyReport)], ['query']),
    'listReportDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'saveReport' : IDL.Func([IDL.Text, DailyReport], [], []),
  });
};

export const init = ({ IDL }) => { return []; };